# Generated by Django 4.2.1 on 2023-05-24 20:43

import api1.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('descricao', models.TextField(max_length=700, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Preço')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=api1.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'widht': 480}}, verbose_name='Foto')),
                ('cep', models.IntegerField(verbose_name='Cep')),
                ('frete', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Frete')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
