# Generated by Django 4.2.1 on 2023-05-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cep',
        ),
    ]
