# Generated by Django 4.2.1 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_remove_produto_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='frete',
        ),
        migrations.AddField(
            model_name='produto',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='Cep'),
        ),
    ]
