# Generated by Django 4.2.1 on 2023-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_alter_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qte_em_estoque',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
